name: fisheri
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.6
  http: ^0.13.3
  json_serializable: ^5.0.0
  json_annotation: ^4.1.0
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_storage: ^10.0.1
  cloud_firestore: ^2.4.0
  flutter_form_builder: ^7.0.0-alpha.2
  form_builder_fields: ^7.0.0-alpha.2
  form_builder_extra_fields: ^7.0.0-alpha.4
  form_builder_validators: ^7.0.0-beta.0
  form_builder_image_picker:
    git:
      url: https://github.com/htbryant94/form_builder_image_picker
  geoflutterfire: ^3.0.1
  google_fonts: ^2.0.0
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  page_view_indicators: ^2.0.0
  basic_utils: ^3.4.0
  webview_flutter: ^2.0.10
  recase: ^4.0.0
  image_picker: ^0.8.3
  uuid: ^3.0.4
  geolocator: ^7.4.0
  modal_bottom_sheet: ^2.0.0
  panorama: ^0.4.1
  url_launcher: ^6.0.9
  get: ^4.3.4
  flutter_google_places:
    git:
      url: https://github.com/imhafeez/flutter_google_places
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.5.0
  build_runner: ^2.1.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - map_style.txt
    - images/lake.jpg
    - images/fisheri_logo.jpg
    - images/logo.png
    - images/question_mark.png
    - images/flags/belgium.png
    - images/flags/croatia.png
    - images/flags/france.png
    - images/flags/germany.png
    - images/flags/netherlands.png
    - images/flags/spain.png
    - images/icons/map_icon.png
    - images/icons/amenities/animal_friendly.png
    - images/icons/amenities/bait.png
    - images/icons/amenities/bait_freezer.png
    - images/icons/amenities/beverages.png
    - images/icons/amenities/camping.png
    - images/icons/amenities/carp_care_equipment_provided.png
    - images/icons/amenities/electricity.png
    - images/icons/amenities/equipment_hire.png
    - images/icons/amenities/food.png
    - images/icons/amenities/food_and_drink.png
    - images/icons/amenities/guests_allowed.png
    - images/icons/amenities/night_fishing.png
    - images/icons/amenities/showers.png
    - images/icons/amenities/snacks.png
    - images/icons/amenities/tackle_hire.png
    - images/icons/amenities/tackle_shop.png
    - images/icons/amenities/takeaway_friendly.png
    - images/icons/amenities/toilets.png
    - images/icons/amenities/trolley_hire.png
    - images/icons/amenities/tuition.png
    - images/icons/amenities/wheelchair_access.png
    - images/icons/amenities/wifi.png
    - images/icons/fishing_types/carp.png
    - images/icons/fishing_types/catfish.png
    - images/icons/fishing_types/coarse.png
    - images/icons/fishing_types/fly.png
    - images/icons/fishing_types/match.png
    - images/icons/fishing_types/predator.png
    - images/icons/fishing_types/sea.png
    - images/icons/map_marker_lake_selected.png
    - images/icons/map_marker_lake_unselected.png
    - images/icons/map_marker_shop_selected.png
    - images/icons/map_marker_shop_unselected.png
    - images/icons/map_marker_embryo.png
    - images/icons/match_positions/1.png
    - images/icons/match_positions/2.png
    - images/icons/match_positions/3.png
    - images/placeholders/events_calendar_create.png
    - images/placeholders/events_calendar_main.png
    - images/placeholders/achievements_screen.png
    - images/placeholders/fishing_license.png
    - images/placeholders/lake_map_view.png
    - images/placeholders/book_tickets.png
    - images/placeholders/panorama.jpg
    - images/placeholders/panorama2.jpg
    - images/placeholders/environment_banner.png
    - images/icons/social_media/facebook.png
    - images/icons/social_media/instagram.png
    - images/icons/social_media/twitter.png
    - images/icons/social_media/youtube.png
    - images/icons/catch_reports.png
    - images/icons/upcoming_events.png
    - images/icons/check_ins_today.png
    - images/icons/map_marker_new.png
    - images/icons/call.png
    - images/icons/website.png
    - images/icons/email.png
    - images/icons/filter.png
    - images/icons/list.png
    - images/icons/map_marker_unselected.png
    - images/icons/2.0x/map_marker_unselected.png
    - images/icons/3.0x/map_marker_unselected.png
    - images/icons/map_marker_selected.png
    - images/icons/2.0x/map_marker_selected.png
    - images/icons/3.0x/map_marker_selected.png
    - images/icons/weather/cloudy.png
    - images/icons/weather/night.png
    - images/icons/weather/raining.png
    - images/icons/weather/raining_heavy.png
    - images/icons/weather/snowing.png
    - images/icons/weather/sunny.png
    - images/icons/weather/sunny_cloudy.png
    - images/icons/weather/thunderstorms.png
    - images/icons/weather/windy.png
    - images/icons/360-degrees.png
    - images/placeholders/swims/swim_1.jpg
    - images/placeholders/swims/swim_2.jpg
    - images/placeholders/swims/swim_3.jpg
    - images/placeholders/swims/swim_4.jpg
    - images/placeholders/swims/swim_5.jpg
    - images/placeholders/swims/swim_6.jpg
    - images/placeholders/shops/Waltham_Cross_1.jpg
    - images/placeholders/shops/Waltham_Cross_2.jpg
    - images/placeholders/shops/Waltham_Cross_3.jpg
    - images/placeholders/shops/Waltham_Cross_4.jpg
    - images/placeholders/shops/Waltham_Cross_5.jpg

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
  - family: CustomIcons
    fonts:
      - asset: assets/fonts/CustomIcons.ttf