name: fisheri
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter:
  http: ^0.12.0+2
  json_serializable: ^3.0.0
  json_annotation: ^2.4.0
  firebase_core: ^0.4.0+5
  firebase_storage: ^3.1.1
  cloud_firestore: ^0.13.0+1
  jaguar_serializer: ^2.2.12
  flutter_form_builder: ^3.5.0
  geoflutterfire: ^2.1.0
  google_fonts: ^0.3.9
  cached_network_image: ^2.0.0
  carousel_slider: ^1.4.1
  page_view_indicators: ^1.3.1
  basic_utils: ^2.5.2
  webview_flutter: ^0.3.21
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.5.0
  build_runner: ^1.2.7
  jaguar_serializer_cli: ^2.2.8

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/lake.jpg
    - images/fisheri_logo.jpg
    - images/logo.png
    - images/fish_1.png
    - images/fish_2.png
    - images/fish_3.png
    - images/fish_4.png
    - images/fish_5.png
    - images/fish_6.png
    - images/fish_7.png
    - images/fish_8.png
    - images/fish_9.png
    - images/fish_10.png
    - images/fish_11.png
    - images/question_mark.png
    - images/galaxy.jpg
    - images/flags/belgium.png
    - images/flags/croatia.png
    - images/flags/france.png
    - images/flags/germany.png
    - images/flags/netherlands.png
    - images/flags/spain.png
    - images/icons/map_icon.png
    - images/icons/amenities/animal_friendly.png
    - images/icons/amenities/camping.png
    - images/icons/amenities/electricity.png
    - images/icons/amenities/food_and_drink.png
    - images/icons/amenities/guests_allowed.png
    - images/icons/amenities/night_fishing.png
    - images/icons/amenities/showers.png
    - images/icons/amenities/takeaway.png
    - images/icons/amenities/toilets.png
    - images/icons/amenities/wheelchair_access.png
    - images/icons/amenities/wifi.png
    - images/placeholders/events_calendar_create.png
    - images/placeholders/events_calendar_main.png
    - images/placeholders/fishing_license.png
    - images/placeholders/lake_map_view.png
    - images/icons/social_media/facebook.png
    - images/icons/social_media/instagram.png
    - images/icons/social_media/twitter.png
    - images/icons/social_media/youtube.png


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
